### ISSUE TITLE
Publish to webcomponents.org

### ISSUE THREAD

**Issue by recrsn** [mercmobily/hot-form#3]
Thanks for this awesome module. Helped me save precious time writing repetitive validation check code for dozens of forms on a project!

Consider publishing to webcomponents.org and/or customelements.io for better visibility, for I found this module accidentally while answering some CSS/Polymer questions on StackOverflow!

**Comment by mercmobily** [comment]
I had no idea anybody other than me was using it!
I updated the documentation, and did a couple of last-minute fixes to it, and fixed the demo.

NOTE: `no-record-id-autoload` is now `no-autoload`. Sorry about the change of API.

Glad somebody is using it. I don't know what I'd do without it... and I just cannot believe people do all this by hand all the time!

**Comment by mercmobily** [comment]
I just wanted to add... do try hot-network too https://github.com/mercmobily/hot-network This is also a HUGE timesaver. I guess I should publish this one too onto webcomponents.org...

**Comment by mercmobily** [comment]
Just checking with you... the change in API didn't affect you too badly, did it? For your reassurance, I am not changing the API again...

**Comment by recrsn** [comment]
No. It didn't.

**Comment by mercmobily** [comment]
OK excellent. I didn't want to disappoint my one user :D 

I published hot-network on webcomponents too:

https://www.webcomponents.org/element/mercmobily/hot-network
